#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

WORKORDER_MATCH="[DBE]-[0-9]*"
# Does either the Story, Defect or Epic number exist?
test "" != "$(egrep "^ *($WORKORDER_MATCH)" "$1" )" || {
echo >&2 "Expected the commit message to start with a V1 Defect, Story or Epic (e.g. D-12345)."
	exit 1
}
# abcdefgh

exit 0